<?php

namespace CdiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuteurRepository extends EntityRepository
{
    /**
     * Méthode pour recherche un auteur ayant un prenom et un nom semblables à ceux passés en paramètres.
     */
    public function recherche($nom){
        $queryBuilder = $this->createQueryBuilder('a');

        if(!is_null($nom)){
            $queryBuilder->andWhere('a.nom LIKE :nom');
            $queryBuilder->setParameter('nom', "%".$nom."%");
        }

        $queryBuilder->setMaxResults(5);

        $res = $queryBuilder->getQuery()->getResult();
        return $res;
    }
}
