<?php

namespace CdiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoteRepository extends EntityRepository
{
    /**
     * Méthode pour rechercher une cote à partir de son nom
     */
    public function recherche($cote){
        $queryBuilder = $this->createQueryBuilder('c');

        if(!is_null($cote)){
            $queryBuilder->andWhere('c.nom LIKE :nom');
            $queryBuilder->setParameter('nom', "%".$cote."%");
        }

        $res = $queryBuilder->getQuery()->getResult();
        return $res;
    }
}
