<?php

namespace CdiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PeriodiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodiqueRepository extends EntityRepository
{
    /**
     * Méthode pour recherche un périodique ayant un nom semblable à celui passé en paramètre.
     */
    public function recherche($nom){
        $queryBuilder = $this->createQueryBuilder('p');
                    
        if(!is_null($nom)){
            $queryBuilder->andWhere('p.nom LIKE :nom');
            $queryBuilder->setParameter('nom', "%".$nom."%");
        }
        
        $queryBuilder->setMaxResults(5);
            
        $res = $queryBuilder->getQuery()->getResult();
        return $res;
    }
}
